version: '2'



services:
  web2:
    build: ./Web_Service
    command: python ./Web_Service/app.py runserver 0.0.0.0:81
    ports:
     - "81:5000"
    volumes:
      - .:/code

  web:
    build: .
    command: python app.py
    ports:
      - "80:5000"
    volumes:
      - .:/code
    links:
      - web2
